#pragma once

#define ENGINE_OPENGL_VERSION_MAJOR 3
#define ENGINE_OPENGL_VERSION_MINOR 3

#define ENGINE_DEFAULT_WINDOW_WIDTH 800
#define ENGINE_DEFAULT_WINDOW_HEIGHT 600
#define ENGINE_DEFAULT_WINDOW_DEPTH 32
#define ENGINE_DEFAULT_WINDOW_REFRESH_RATE 60
#define ENGINE_DEFAULT_FULLSCREEN 0
#define ENGINE_DEFAULT_GAME_MODE 0